# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9de1f5f8763de4ec6c2296215c5268b6b8d4b5b403187bee893ff49b06d6f66e4a0eebbea4067bfec8ec0cb92d1f454b3a2eb683b4ef7b784612ccd4d5c5b7ca

test:
  secret_key_base: 5baee6fd8219a97ddb60b53a5beb3cd36294ef7781692d17566db12f0b986070cb33ebdf56dba23522888fe349d2e3be656775c61a8c7862302bd753f6895ca8
  twitter_consumer_key: gfFZI1hGCtKqV4fVYcge7Ygv8
  twitter_consumer_secret: 6yRePn1f1bG1Skx06Py1ZYGu77AGoNWJGmMtiuxye83kVuoUqM
  twitter_access_token: 122639798-Nviw5UWMSkp1AblJXbSkPGDnRxilR2xLRS9NBPqu
  twitter_access_token_secret: dnGpC5NesmRGqEMdoQAOqRCtgGG1jbKAaDnH2qWWvfApx

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
